name=(input("Name: "))
age=(input("age = "))
new_age=(int(age) + 1)
is_student=(input("Is Student: "))
print('Name: ' + (name))
print("Age: " + (age))
print("New Age: " + str(new_age))
if is_student == ("yes"): print("Is Student: True")
if is_student == ("no"): print("Is Student: Fauls")